version: '3'
services:
  api:
    hostname: meditrax-api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - '8000:8000'
    # networks:
    #   mongodb_mongors-network:

  # client:
  #   depends_on:
  #     - api
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./client
  #     args:
  #       ENABLED_MODULES: brotli
  #   ports:
  #     - '8000:80'

# networks:
#   mongodb_mongors-network:
#     external: true