// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AchievementBadge struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IconURL     string `json:"iconUrl"`
	CreatedAt   string `json:"createdAt"`
}

type AchievementBadgeDetail struct {
	BadgeID     string `json:"badgeId"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IconURL     string `json:"iconUrl"`
<<<<<<< HEAD
	CreatedAt   string `json:"created_at"`
=======
	CreatedAt   string `json:"createdAt"`
}

type ActivityLog struct {
	ID            string `json:"id"`
	UserID        string `json:"userId"`
	ActivityType  string `json:"activityType"`
	Description   string `json:"description"`
	ChangedObject string `json:"changedObject"`
	ChangedField  string `json:"changedField"`
	From          string `json:"from"`
	To            string `json:"to"`
	Timestamp     string `json:"timestamp"`
}

type ActivityLogDetail struct {
	LogID         string `json:"logId"`
	ActivityType  string `json:"activityType"`
	Description   string `json:"description"`
	ChangedObject string `json:"changedObject"`
	ChangedField  string `json:"changedField"`
	From          string `json:"from"`
	To            string `json:"to"`
	Timestamp     string `json:"timestamp"`
>>>>>>> 01096166741546756a9456fc584388602358902c
}

type AddFamilyMemberResponse struct {
	MemberID string `json:"memberId"`
	Message  string `json:"message"`
}

type AddHealthMetricResponse struct {
	MetricID string `json:"metricId"`
	Message  string `json:"message"`
}

type AddMedicalRecordResponse struct {
	RecordID string `json:"recordId"`
	Message  string `json:"message"`
}

type AddMedicationResponse struct {
	MedicationID string `json:"medicationId"`
	Message      string `json:"message"`
}

type AwardAchievementResponse struct {
	UserAchievementID string `json:"userAchievementId"`
	Message           string `json:"message"`
}

type CreateAchievementBadgeResponse struct {
	BadgeID string `json:"badgeId"`
	Message string `json:"message"`
}

type CreateMedicationReminderResponse struct {
	ReminderID string `json:"reminderId"`
	Message    string `json:"message"`
}

type CreateTreatmentScheduleResponse struct {
	ScheduleID string `json:"scheduleId"`
	Message    string `json:"message"`
}

type CreateUserResponse struct {
	UserID  string `json:"userId"`
	Message string `json:"message"`
}

type DeleteFamilyMemberResponse struct {
	Message string `json:"message"`
}

type DeleteHealthMetricResponse struct {
	Message string `json:"message"`
}

type DeleteMedicalRecordResponse struct {
	Message string `json:"message"`
}

type DeleteMedicationReminderResponse struct {
	Message string `json:"message"`
}

type DeleteMedicationResponse struct {
	Message string `json:"message"`
}

type DeleteTreatmentScheduleResponse struct {
	Message string `json:"message"`
}

type DeleteUserResponse struct {
	Message string `json:"message"`
}

<<<<<<< HEAD
=======
type EvaluateHealthRiskAssessmentResponse struct {
	AssessmentID    string `json:"assessmentId"`
	RiskLevel       string `json:"riskLevel"`
	Recommendations string `json:"recommendations"`
}

>>>>>>> 01096166741546756a9456fc584388602358902c
type FamilyMember struct {
	ID            string `json:"id"`
	UserID        string `json:"userId"`
	PatientUserID string `json:"patient_userId"`
	Relationship  string `json:"relationship"`
	AccessLevel   int    `json:"accessLevel"`
	CreatedAt     string `json:"createdAt"`
}

type FamilyMemberDetail struct {
<<<<<<< HEAD
	MemberID      string `json:"memberId"`
	RelatedUserID string `json:"relatedUserId"`
	Relationship  string `json:"relationship"`
	AccessLevel   int    `json:"accessLevel"`
=======
	MemberID     string `json:"memberId"`
	FamilyID     string `json:"familyId"`
	Name         string `json:"name"`
	PhoneNumber  string `json:"phoneNumber"`
	Relationship string `json:"relationship"`
	AccessLevel  int    `json:"accessLevel"`
}

type FilledQuestionnaire struct {
	QuestionnaireID int         `json:"questionnaireId"`
	Responses       []*Response `json:"responses"`
>>>>>>> 01096166741546756a9456fc584388602358902c
}

type FoodRecommendation struct {
	Name string `json:"name"`
}

type FoodSpec struct {
	Name    string  `json:"name"`
	Value   float64 `json:"value"`
	Unit    string  `json:"unit"`
	HowHigh float64 `json:"howHigh"`
}

type FoodSpecs struct {
	Specs        []*FoodSpec `json:"specs"`
	HowRecommend float64     `json:"howRecommend"`
}

type HealthMetric struct {
	ID         string  `json:"id"`
<<<<<<< HEAD
	UserID     string  `json:"user_id"`
	MetricType string  `json:"metric_type"`
	Value      float64 `json:"value"`
	Unit       string  `json:"unit"`
	RecordedAt string  `json:"recorded_at"`
	CreatedAt  string  `json:"created_at"`
=======
	UserID     string  `json:"userId"`
	MetricType string  `json:"metricType"`
	Value      float64 `json:"value"`
	Unit       string  `json:"unit"`
	RecordedAt string  `json:"recordedAt"`
	CreatedAt  string  `json:"createdAt"`
>>>>>>> 01096166741546756a9456fc584388602358902c
}

type HealthMetricDetail struct {
	MetricID   string  `json:"metricId"`
	MetricType string  `json:"metricType"`
	Value      float64 `json:"value"`
	Unit       string  `json:"unit"`
	RecordedAt string  `json:"recordedAt"`
}

type HealthResponse struct {
	QuestionID int     `json:"questionId"`
	Choice     string  `json:"choice"`
	Answer     *string `json:"answer,omitempty"`
}

type HealthRiskAssessment struct {
<<<<<<< HEAD
	ID                string `json:"id"`
	UserID            string `json:"user_id"`
	QuestionnaireData string `json:"questionnaire_data"`
	RiskLevel         string `json:"risk_level"`
	Recommendations   string `json:"recommendations"`
	CreatedAt         string `json:"created_at"`
=======
	ID                string            `json:"id"`
	UserID            string            `json:"userId"`
	QuestionnaireData []*HealthResponse `json:"questionnaireData"`
	RiskLevel         string            `json:"riskLevel"`
	Recommendations   string            `json:"recommendations"`
	CreatedAt         string            `json:"createdAt"`
>>>>>>> 01096166741546756a9456fc584388602358902c
}

type HealthRiskAssessmentDetailResponse struct {
	AssessmentID      string            `json:"assessmentId"`
	QuestionnaireData []*HealthResponse `json:"questionnaireData"`
	RiskLevel         string            `json:"riskLevel"`
	Recommendations   string            `json:"recommendations"`
	CreatedAt         string            `json:"createdAt"`
}

type LoginUserResponse struct {
	UserID  string `json:"userId"`
	Token   *Token `json:"token"`
	Message string `json:"message"`
}

type MedicalRecord struct {
	ID         string `json:"id"`
<<<<<<< HEAD
	UserID     string `json:"user_id"`
	RecordType string `json:"record_type"`
	Content    string `json:"content"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
=======
	UserID     string `json:"userId"`
	RecordType string `json:"recordType"`
	Content    string `json:"content"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
>>>>>>> 01096166741546756a9456fc584388602358902c
}

type MedicalRecordDetail struct {
	RecordID   string `json:"recordId"`
	RecordType string `json:"recordType"`
	Content    string `json:"content"`
	CreatedAt  string `json:"createdAt"`
}

type Medication struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Dosage    float64 `json:"dosage"`
	Unit      string  `json:"unit"`
	Frequency string  `json:"frequency"`
	Inventory float64 `json:"inventory"`
<<<<<<< HEAD
	UserID    string  `json:"user_id"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
=======
	UserID    string  `json:"userId"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
>>>>>>> 01096166741546756a9456fc584388602358902c
}

type MedicationDetail struct {
	MedicationID string  `json:"medicationId"`
	Name         string  `json:"name"`
	Dosage       float64 `json:"dosage"`
	Unit         string  `json:"unit"`
	Frequency    string  `json:"frequency"`
	Inventory    float64 `json:"inventory"`
}

type MedicationReminder struct {
	ID           string `json:"id"`
	MedicationID string `json:"medicationId"`
	UserID       string `json:"userId"`
	ReminderTime string `json:"reminderTime"`
	IsTaken      bool   `json:"isTaken"`
	CreatedAt    string `json:"createdAt"`
}

type MedicationReminderDetail struct {
	ReminderID   string `json:"reminderId"`
	MedicationID string `json:"medicationId"`
	ReminderTime string `json:"reminderTime"`
	IsTaken      bool   `json:"isTaken"`
}

type Mutation struct {
}

type PasswordChange struct {
	ID        string `json:"id"`
	User      string `json:"user"`
	Token     string `json:"token"`
	CreatedAt string `json:"createdAt"`
}

type PatientDetail struct {
	PatientID    string `json:"patientId"`
	Name         string `json:"name"`
	PhoneNumber  string `json:"phoneNumber"`
	Relationship string `json:"relationship"`
	AccessLevel  int    `json:"accessLevel"`
}

type ProfileDetail struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	PhoneNumber string `json:"phoneNumber"`
	Role        string `json:"role"`
	CreatedAt   string `json:"createdAt"`
}

type Query struct {
}

type Question struct {
<<<<<<< HEAD
	Question     string   `json:"question"`
	QuestionType int      `json:"questionType"`
	Choices      []string `json:"choices"`
	Answer       string   `json:"answer"`
=======
	QuestionID   int      `json:"questionId"`
	Question     string   `json:"question"`
	QuestionType int      `json:"questionType"`
	Choices      []string `json:"choices,omitempty"`
>>>>>>> 01096166741546756a9456fc584388602358902c
}

type QuestionnaireObject struct {
	QuestionnaireID int         `json:"questionnaireId"`
	Data            []*Question `json:"data"`
}

type RecordObject struct {
	Data string `json:"data"`
}

type RequestPasswordResetResponse struct {
	Message string `json:"message"`
}

type ResetPasswordResponse struct {
	Message string `json:"message"`
}

type Response struct {
	QuestionID int     `json:"questionId"`
	Choice     string  `json:"choice"`
	Answer     *string `json:"answer,omitempty"`
}

type ShareProfileResponse struct {
	Message string `json:"message"`
}

type TakeMedicationResponse struct {
	Message string `json:"message"`
}

type Token struct {
	ID                 string `json:"id"`
	User               string `json:"user"`
	AccessToken        string `json:"accessToken"`
	RefreshToken       string `json:"refreshToken"`
	AccessTokenExpiry  string `json:"accessTokenExpiry"`
	RefreshTokenExpiry string `json:"refreshTokenExpiry"`
	Device             string `json:"device"`
	CreatedAt          string `json:"createdAt"`
	UpdatedAt          string `json:"updatedAt"`
}

type TreatmentSchedule struct {
	ID            string  `json:"id"`
<<<<<<< HEAD
	UserID        string  `json:"user_id"`
=======
	UserID        string  `json:"userId"`
	TreatmentType string  `json:"treatmentType"`
	ScheduledTime string  `json:"scheduledTime"`
	Location      string  `json:"location"`
	Notes         *string `json:"notes,omitempty"`
}

type TreatmentScheduleDetail struct {
	ScheduleID    string  `json:"scheduleId"`
>>>>>>> 01096166741546756a9456fc584388602358902c
	TreatmentType string  `json:"treatmentType"`
	ScheduledTime string  `json:"scheduledTime"`
	Location      string  `json:"location"`
	Notes         *string `json:"notes,omitempty"`
}

<<<<<<< HEAD
type TreatmentScheduleDetail struct {
	ScheduleID    string  `json:"scheduleId"`
	TreatmentType string  `json:"treatmentType"`
	ScheduledTime string  `json:"scheduledTime"`
	Location      string  `json:"location"`
	Notes         *string `json:"notes,omitempty"`
=======
type UnshareProfileResponse struct {
	Message string `json:"message"`
>>>>>>> 01096166741546756a9456fc584388602358902c
}

type UpdateFamilyMemberResponse struct {
	MemberID string `json:"memberId"`
	Message  string `json:"message"`
}

type UpdateHealthMetricResponse struct {
	MetricID string `json:"metricId"`
	Message  string `json:"message"`
}

type UpdateMedicalRecordResponse struct {
	RecordID string `json:"recordId"`
	Message  string `json:"message"`
}

type UpdateMedicationReminderResponse struct {
	ReminderID string `json:"reminderId"`
	Message    string `json:"message"`
}

type UpdateMedicationResponse struct {
	MedicationID string `json:"medicationId"`
	Message      string `json:"message"`
}

type UpdateTreatmentScheduleResponse struct {
	ScheduleID string `json:"scheduleId"`
	Message    string `json:"message"`
}

type UpdateUserResponse struct {
	UserID  string `json:"userId"`
	Message string `json:"message"`
}

type User struct {
	ID          string  `json:"id"`
	PhoneNumber string  `json:"phoneNumber"`
	Password    string  `json:"password"`
	Name        string  `json:"name"`
	Points      float64 `json:"points"`
<<<<<<< HEAD
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	LastLogin   string  `json:"last_login"`
=======
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	LastLogin   string  `json:"lastLogin"`
>>>>>>> 01096166741546756a9456fc584388602358902c
	Status      int     `json:"status"`
	Role        string  `json:"role"`
}

type UserAchievement struct {
	ID        string `json:"id"`
	UserID    string `json:"userId"`
	BadgeID   string `json:"badgeId"`
	EarnedAt  string `json:"earnedAt"`
	CreatedAt string `json:"createdAt"`
}

type UserAchievementDetail struct {
	UserAchievementID string `json:"userAchievementId"`
	BadgeID           string `json:"badgeId"`
	EarnedAt          string `json:"earnedAt"`
}

type UserDetailResponse struct {
	UserID      string  `json:"userId"`
	PhoneNumber string  `json:"phoneNumber"`
	Name        string  `json:"name"`
	Points      float64 `json:"points"`
	Role        string  `json:"role"`
	CreatedAt   string  `json:"createdAt"`
	LastLogin   *string `json:"lastLogin,omitempty"`
}

type UserPointRecord struct {
	ID           string  `json:"id"`
<<<<<<< HEAD
	UserID       string  `json:"user_id"`
=======
	UserID       string  `json:"userId"`
>>>>>>> 01096166741546756a9456fc584388602358902c
	PointsEarned float64 `json:"pointsEarned"`
	Reason       string  `json:"reason"`
	EarnedAt     string  `json:"earnedAt"`
}

type UserPointRecordDetail struct {
	RecordID     string  `json:"recordId"`
	PointsEarned float64 `json:"pointsEarned"`
	Reason       string  `json:"reason"`
	EarnedAt     string  `json:"earnedAt"`
}

type EarnPointsResponse struct {
	UpdatedPoints float64 `json:"updatedPoints"`
	Message       string  `json:"message"`
}
